# Generated by Django 5.0.4 on 2024-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_billet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sieges_reserves',
            field=models.IntegerField(default=0),
        ),
    ]
