# Generated by Django 5.0.4 on 2024-05-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_billet', '0002_car_sieges_reserves'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Numéro_siège',
            field=models.IntegerField(default=50),
        ),
    ]
