# Generated by Django 5.0.4 on 2024-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_billet', '0004_remove_billet_date_voyage_remove_reservation_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='Prix',
            field=models.FloatField(),
        ),
    ]
