# Generated by Django 5.0.4 on 2024-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_billet', '0005_alter_billet_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='Prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='Prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
