# Generated by Django 5.0.4 on 2024-05-30 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_billet', '0006_alter_billet_prix_alter_trajet_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='billet',
        ),
        migrations.AddField(
            model_name='billet',
            name='Reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reservation_billet.reservation'),
            preserve_default=False,
        ),
    ]
