# Generated by Django 5.0.4 on 2024-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_billet', '0007_remove_reservation_billet_billet_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='Prix',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='Prix',
            field=models.FloatField(),
        ),
    ]
